// Block display information (icons and labels for UI)
export const BLOCK_DISPLAY = {
  cube: { icon: '▢', label: 'Cube' },
  slab: { icon: '▃', label: 'Slab' },
  slabTop: { icon: '▀', label: 'Slab Top' },
  quarter: { icon: '◱', label: 'Quarter' },
  quarterTall: { icon: '◰', label: 'Qtr Tall' },
  halfX: { icon: '▐', label: 'Half X' },
  halfZ: { icon: '▄', label: 'Half Z' },
  halfCorner: { icon: '◼', label: 'Half Crn' },
  pillar: { icon: '▪', label: 'Pillar' },
  pillar2: { icon: '∙', label: 'Pillar S' },
  pillar4: { icon: '·', label: 'Pillar XS' },
  pillarRound: { icon: '◯', label: 'Round Pil' },
  pillarRound2: { icon: '◦', label: 'Round S' },
  beamX: { icon: '═', label: 'Beam X' },
  beam2X: { icon: '─', label: 'Beam X S' },
  beam4X: { icon: '╌', label: 'Beam X XS' },
  beamZ: { icon: '║', label: 'Beam Z' },
  beam2Z: { icon: '│', label: 'Beam Z S' },
  beam4Z: { icon: '╎', label: 'Beam Z XS' },
  beamDiag: { icon: '╲', label: 'Beam Diag' },
  beamXLow: { icon: '▬', label: 'Beam X Lo' },
  beam2XLow: { icon: '―', label: 'Beam X LoS' },
  beamZLow: { icon: '▮', label: 'Beam Z Lo' },
  beam2ZLow: { icon: '┃', label: 'Beam Z LoS' },
  wall: { icon: '▯', label: 'Wall' },
  wall4: { icon: '│', label: 'Wall Thin' },
  wall8: { icon: '┃', label: 'Wall XThin' },
  panel: { icon: '|', label: 'Panel' },
  wallFront: { icon: '▌', label: 'Wall Front' },
  wallBack: { icon: '▐', label: 'Wall Back' },
  wallCorner: { icon: '┐', label: 'Corner' },
  wallCornerInner: { icon: '└', label: 'Inner Crn' },
  wallJunction: { icon: '◤', label: 'Junction' },
  wedge: { icon: '◿', label: 'Wedge' },
  wedgeLow: { icon: '⊿', label: 'Wedge Low' },
  wedgeFlat: { icon: '▱', label: 'Wedge Flat' },
  wedgeTop: { icon: '◺', label: 'Wedge Top' },
  wedgeLowTop: { icon: '⊿', label: 'Wdg Low Top' },
  wedgeFlatTop: { icon: '▱', label: 'Wdg Flat Top' },
  wedgeCorner: { icon: '◢', label: 'Wdg Corner' },
  wedgeInner: { icon: '◣', label: 'Wdg Inner' },
  wedge4x2: { icon: '◿', label: 'Wdg 4x2' },
  wedge4x2Top: { icon: '◺', label: 'Wdg 4x2 Top' },
  wedge2x2: { icon: '◿', label: 'Wdg 2x2' },
  wedge2x2Top: { icon: '◺', label: 'Wdg 2x2 Top' },
  wedgeHalf: { icon: '◿', label: 'Wdg Half' },
  wedgeHalfTop: { icon: '◺', label: 'Wdg Half Top' },
  wedgeCornerLow: { icon: '◢', label: 'Wdg Crn Lo' },
  wedgeCornerFlat: { icon: '◢', label: 'Wdg Crn Flat' },
  stairs: { icon: '⌐', label: 'Stairs 2' },
  stairs4: { icon: '▤', label: 'Stairs 4' },
  stairs8: { icon: '▥', label: 'Stairs 8' },
  stairsCorner: { icon: '⌏', label: 'Stair Crn' },
  stairsCornerInner: { icon: '⌎', label: 'Stair Inn' },
  cylinder: { icon: '○', label: 'Cylinder' },
  cylinderHalf: { icon: '◗', label: 'Half Cyl' },
  cone: { icon: '△', label: 'Cone' },
  sphere: { icon: '●', label: 'Sphere' },
  dome: { icon: '◠', label: 'Dome' },
  pyramid: { icon: '◭', label: 'Pyramid' },
  octagon: { icon: '⬡', label: 'Octagon' },
  tube: { icon: '◎', label: 'Tube' },
  arch: { icon: '∩', label: 'Arch' },
  archLow: { icon: '⌒', label: 'Arch Low' },
  archWide: { icon: '⌢', label: 'Arch Wide' },
  archHalf: { icon: '⌓', label: 'Arch Half' },
  cross: { icon: '✚', label: 'Cross' },
  frame: { icon: '□', label: 'Frame' },
  fence: { icon: '╫', label: 'Fence' },
  fenceZ: { icon: '╪', label: 'Fence Z' },
  railing: { icon: '⊢', label: 'Railing' },
  railingZ: { icon: '⊣', label: 'Railing Z' },
  pipeX: { icon: '━', label: 'Pipe X' },
  pipeY: { icon: '┃', label: 'Pipe Y' },
  pipeZ: { icon: '─', label: 'Pipe Z' },
  pipeElbow: { icon: '┘', label: 'Elbow 1' },
  pipeElbow2: { icon: '└', label: 'Elbow 2' },
  pipeElbow3: { icon: '┌', label: 'Elbow 3' },
  pipeElbow4: { icon: '┐', label: 'Elbow 4' },
  pipeCross: { icon: '┼', label: 'Cross' },
  pipeT: { icon: '┬', label: 'T Horiz' },
  pipeTY: { icon: '⊥', label: 'T Vert' },
  prism: { icon: '▲', label: 'Prism' },
  lShape: { icon: '⌐', label: 'L Shape' },
  tShape: { icon: '⊥', label: 'T Shape' },
  cShape: { icon: '⊏', label: 'C Shape' },
  ledge: { icon: '⌐', label: 'Ledge' },
  gutter: { icon: '⊔', label: 'Gutter' },
  capital: { icon: '⊓', label: 'Capital' },
  base: { icon: '⊔', label: 'Base' },
  windowFrame: { icon: '⊞', label: 'Window' },
  doorFrame: { icon: '⊡', label: 'Door' },
  cornice: { icon: '⌐', label: 'Cornice' },
  column: { icon: '⫿', label: 'Column' },
  baluster: { icon: '⌇', label: 'Baluster' },
  windowSill: { icon: '⌐', label: 'Win Sill' },
  shingle: { icon: '▱', label: 'Shingle' },
  chimney: { icon: '⌓', label: 'Chimney' },
  buttress: { icon: '◢', label: 'Buttress' },
  bench: { icon: '⊔', label: 'Bench' },
  table: { icon: '⊓', label: 'Table' },
  chair: { icon: '⌐', label: 'Chair' },
  barrel: { icon: '⬭', label: 'Barrel' },
  planter: { icon: '⊔', label: 'Planter' },
  ladder: { icon: '⊞', label: 'Ladder' },
  crate: { icon: '▣', label: 'Crate' },
  crateOpen: { icon: '☐', label: 'Crate Open' },
  crateLarge: { icon: '▢', label: 'Crate Lrg' },
  pallet: { icon: '⊟', label: 'Pallet' },
  shelfUnit: { icon: '⊞', label: 'Shelf' },
  locker: { icon: '▣', label: 'Locker' },
  cabinet: { icon: '▤', label: 'Cabinet' },
  cardboardBox: { icon: '□', label: 'Cardboard' },
  sack: { icon: '◠', label: 'Sack' },
  tank: { icon: '⬭', label: 'Tank' },
  valve: { icon: '✱', label: 'Valve' },
  vent: { icon: '⊞', label: 'Vent' },
  iBeam: { icon: '⊥', label: 'I-Beam' },
  catwalk: { icon: '⊟', label: 'Catwalk' },
  transformer: { icon: '⌂', label: 'Transform' },
  powerBox: { icon: '⚡', label: 'Power Box' },
  conduit: { icon: '━', label: 'Conduit' },
  conduitCorner: { icon: '┘', label: 'Conduit Crn' },
  outlet: { icon: '⊡', label: 'Outlet' },
  switchBox: { icon: '⊟', label: 'Switch' },
  fuseBox: { icon: '⊞', label: 'Fuse Box' },
  cable: { icon: '─', label: 'Cable' },
  lightFixture: { icon: '☼', label: 'Light' },
  cableHanging: { icon: '⌒', label: 'Cable Sag' },
  cableDroop: { icon: '⌓', label: 'Cable Drop' },
  cableLoop: { icon: '∞', label: 'Cable Coil' },
  rock: { icon: '●', label: 'Rock' },
  bush: { icon: '❁', label: 'Bush' },
  logX: { icon: '═', label: 'Log X' },
  logZ: { icon: '║', label: 'Log Z' },
  acUnit: { icon: '⊞', label: 'AC Unit' },
  solarPanel: { icon: '⊟', label: 'Solar' },
  antenna: { icon: '⌇', label: 'Antenna' },
  barrier: { icon: '▬', label: 'Barrier' },
  quarterPipe: { icon: '⌒', label: 'Qtr Pipe' },
  bowl: { icon: '◠', label: 'Bowl' },
  hexagon: { icon: '⬡', label: 'Hexagon' },
  roundedCube: { icon: '▢', label: 'Rounded' },
  chamfer: { icon: '◇', label: 'Chamfer' },
  merlon: { icon: '⊓', label: 'Merlon' },
  arrowSlit: { icon: '⊔', label: 'Arrow Slit' },
  torch: { icon: '♨', label: 'Torch' },
  chain: { icon: '⫿', label: 'Chain' },
  rampCurved: { icon: '⌒', label: 'Ramp Curved' },
  rampCurvedLow: { icon: '⌒', label: 'Ramp Crv Lo' },
  rampCurvedCorner: { icon: '◜', label: 'Ramp Crv Crn' },
  roofPeak: { icon: '⌂', label: 'Roof Peak' },
  roofPeakLow: { icon: '⌂', label: 'Roof Pk Lo' },
  roofHip: { icon: '◬', label: 'Roof Hip' },
  slabSlope: { icon: '▱', label: 'Slab Slope' },
  slabSlopeTop: { icon: '▱', label: 'Slab Slp Top' },
  channel: { icon: '⊔', label: 'Channel' },
  channelCorner: { icon: '⌐', label: 'Channel Crn' },
  channelEnd: { icon: '⊓', label: 'Channel End' },
  cubeBevel: { icon: '◇', label: 'Cube Bevel' },
  step: { icon: '▁', label: 'Step' },
  platform: { icon: '▔', label: 'Platform' },
  post: { icon: '┃', label: 'Post' },
  bollard: { icon: '⏺', label: 'Bollard' },
  crossBeam: { icon: '╋', label: 'Cross Beam' },
  truss: { icon: '⋈', label: 'Truss' },
  parapet: { icon: '▄', label: 'Parapet' },
  crenellation: { icon: '⊓⊓', label: 'Crenellation' },
  trianglePrism: { icon: '△', label: 'Tri Prism' },
  triangleRight: { icon: '◿', label: 'Tri Right' },
  triangleEqui: { icon: '▲', label: 'Tri Equi' },
  tetrahedron: { icon: '◬', label: 'Tetrahedron' },
  pentahedron: { icon: '◭', label: 'Pentahedron' },
  stairsSingle: { icon: '⌐', label: 'Single Step' },
  landing: { icon: '▁', label: 'Landing' },
  spiralStep: { icon: '◠', label: 'Spiral Step' },
  torus: { icon: '◎', label: 'Torus' },
  capsule: { icon: '⬬', label: 'Capsule' },
  hemisphere: { icon: '◠', label: 'Hemisphere' },
  egg: { icon: '⬮', label: 'Egg' },
  gothicArch: { icon: '⋀', label: 'Gothic Arch' },
  flatArch: { icon: '⌐', label: 'Flat Arch' },
  keystone: { icon: '⌓', label: 'Keystone' },
  downspout: { icon: '│', label: 'Downspout' },
  star: { icon: '★', label: 'Star' },
  heart: { icon: '♥', label: 'Heart' },
  diamond: { icon: '◆', label: 'Diamond' },
  cornerTrim: { icon: '⌐', label: 'Corner Trim' },
  edgeTrim: { icon: '─', label: 'Edge Trim' },
  moldingX: { icon: '═', label: 'Molding X' },
  moldingZ: { icon: '║', label: 'Molding Z' },
  bracket: { icon: '⌐', label: 'Bracket' },
  finial: { icon: '♦', label: 'Finial' },
  pediment: { icon: '⌂', label: 'Pediment' },
  dentil: { icon: '▪', label: 'Dentil' },
  awning: { icon: '⌒', label: 'Awning' },
  canopy: { icon: '▔', label: 'Canopy' },
  pergola: { icon: '≡', label: 'Pergola' },
  tarp: { icon: '▭', label: 'Tarp' },
  umbrella: { icon: '☂', label: 'Umbrella' },
  stool: { icon: '⌓', label: 'Stool' },
  shelf: { icon: '▁', label: 'Shelf' },
  bed: { icon: '▭', label: 'Bed' },
  desk: { icon: '⊓', label: 'Desk' },
  bin: { icon: '⊔', label: 'Bin' },
  dumpster: { icon: '▣', label: 'Dumpster' },
  grateFloor: { icon: '⊞', label: 'Grate Floor' },
  ductX: { icon: '═', label: 'Duct X' },
  ductZ: { icon: '║', label: 'Duct Z' },
  ductCorner: { icon: '╔', label: 'Duct Corner' },
  hopper: { icon: '▽', label: 'Hopper' },
  conveyor: { icon: '═', label: 'Conveyor' },
  spotlight: { icon: '◉', label: 'Spotlight' },
  bulb: { icon: '●', label: 'Bulb' },
  stump: { icon: '◯', label: 'Stump' },
  boulder: { icon: '◎', label: 'Boulder' },
  grass: { icon: '⌇', label: 'Grass' },
  flower: { icon: '✿', label: 'Flower' },
  trafficCone: { icon: '▲', label: 'Traffic Cone' },
  sign: { icon: '⊤', label: 'Sign' },
  monitor: { icon: '▢', label: 'Monitor' },
  speaker: { icon: '◉', label: 'Speaker' },
  gem: { icon: '◇', label: 'Gem' },
  crystal: { icon: '◇', label: 'Crystal' },
  pill: { icon: '⬬', label: 'Pill' },
  rampStraight: { icon: '⌒', label: 'Ramp Straight' },
  rampWide: { icon: '⌒', label: 'Ramp Wide' },
  roofCorner: { icon: '◢', label: 'Roof Corner' },
  roofValley: { icon: '◣', label: 'Roof Valley' },
  gable: { icon: '△', label: 'Gable' },
  drain: { icon: '◎', label: 'Drain' },
  grate: { icon: '⊞', label: 'Grate' },
  shield: { icon: '⛊', label: 'Shield' },
  banner: { icon: '⚐', label: 'Banner' },
  portcullis: { icon: '⊞', label: 'Portcullis' },
  wheel: { icon: '◎', label: 'Wheel' },
  axle: { icon: '─', label: 'Axle' },
  seat: { icon: '⌐', label: 'Seat' },
  hull: { icon: '⌒', label: 'Hull' },
  propeller: { icon: '✳', label: 'Propeller' },
  wing: { icon: '▷', label: 'Wing' },
  derrickLeg: { icon: '╱', label: 'Derrick Leg' },
  derrickCross: { icon: '╳', label: 'Derrick X' },
  derrickPlatform: { icon: '▭', label: 'Derrick Plat' },
  pumpJack: { icon: '⌓', label: 'Pump Jack' },
  pumpBase: { icon: '▭', label: 'Pump Base' },
  oilTank: { icon: '⬭', label: 'Oil Tank' },
  oilTankSmall: { icon: '⬮', label: 'Tank Small' },
  wellHead: { icon: '⊥', label: 'Well Head' },
  pipelineX: { icon: '═', label: 'Pipeline X' },
  pipelineZ: { icon: '║', label: 'Pipeline Z' },
  oilBarrel: { icon: '⬭', label: 'Oil Barrel' },
  // Pipe elbows with correct naming
  pipeElbowXZ: { icon: '┘', label: 'Elbow XZ 1' },
  pipeElbowXZ2: { icon: '└', label: 'Elbow XZ 2' },
  pipeElbowXZ3: { icon: '┌', label: 'Elbow XZ 3' },
  pipeElbowXZ4: { icon: '┐', label: 'Elbow XZ 4' },
  pipeElbowXY: { icon: '⌐', label: 'Elbow XY' },
  pipeElbowXY2: { icon: '⌐', label: 'Elbow XY 2' },
  pipeElbowYZ: { icon: '⌐', label: 'Elbow YZ' },
  pipeElbowYZ2: { icon: '⌐', label: 'Elbow YZ 2' },
  pipeTZ: { icon: '⊤', label: 'T Pipe Z' },
  // Conduit variants
  conduitX: { icon: '━', label: 'Conduit X' },
  conduitY: { icon: '┃', label: 'Conduit Y' },
  conduitZ: { icon: '─', label: 'Conduit Z' },
  conduitElbow: { icon: '┘', label: 'Cond Elbow' },
  conduitElbowY: { icon: '⌐', label: 'Cond Elbow Y' },
  conduitT: { icon: '┬', label: 'Conduit T' },
  // Cable variants
  cableX: { icon: '─', label: 'Cable X' },
  cableY: { icon: '│', label: 'Cable Y' },
  cableZ: { icon: '─', label: 'Cable Z' },
  cableElbow: { icon: '┘', label: 'Cable Elbow' },
  cableElbowY: { icon: '⌐', label: 'Cable Elbow Y' },
  cableT: { icon: '┬', label: 'Cable T' },
  // Rock variations
  rockSmall: { icon: '◦', label: 'Rock Small' },
  rockLarge: { icon: '◎', label: 'Rock Large' },
  rockFlat: { icon: '▭', label: 'Rock Flat' },
  rockTall: { icon: '▮', label: 'Rock Tall' },
  rockJagged: { icon: '◬', label: 'Rock Jagged' },
  rockCluster: { icon: '◎◎', label: 'Rock Cluster' },
  rockPile: { icon: '◉', label: 'Rock Pile' },
  pebbles: { icon: '∴', label: 'Pebbles' },
  slate: { icon: '▭', label: 'Slate' },
  // Crystal variations
  crystalSmall: { icon: '◇', label: 'Crystal Small' },
  crystalLarge: { icon: '◆', label: 'Crystal Large' },
  crystalCluster: { icon: '◇◇', label: 'Crystal Cluster' },
  crystalSpike: { icon: '▲', label: 'Crystal Spike' },
  crystalFlat: { icon: '⬡', label: 'Crystal Flat' },
  crystalShard: { icon: '◇', label: 'Crystal Shard' },
  crystalFormation: { icon: '◆◇', label: 'Crystal Form' },
  // Cave/Nature
  stalactite: { icon: '▼', label: 'Stalactite' },
  stalagmite: { icon: '▲', label: 'Stalagmite' },
  mushroom: { icon: '🍄', label: 'Mushroom' },
  mushroomCluster: { icon: '🍄🍄', label: 'Mushroom Clst' },
  moss: { icon: '≈', label: 'Moss' },
  vine: { icon: '⌇', label: 'Vine' },
  coral: { icon: '⚘', label: 'Coral' },
  // Munitions
  bullet: { icon: '⌐', label: 'Bullet' },
  bulletTip: { icon: '▲', label: 'Bullet Tip' },
  shellCasing: { icon: '◯', label: 'Shell Casing' },
  cartridgeBox: { icon: '⊞', label: 'Cartridge Box' },
  magazine: { icon: '▮', label: 'Magazine' },
  magazineDrum: { icon: '◎', label: 'Drum Mag' },
  ammoCan: { icon: '▣', label: 'Ammo Can' },
  ammoCrate: { icon: '▤', label: 'Ammo Crate' },
  gunpowderBarrel: { icon: '⬭', label: 'Powder Barrel' },
  artilleryShell: { icon: '↑', label: 'Artillery Shell' },
  mortarShell: { icon: '⌃', label: 'Mortar Shell' },
  rocketShell: { icon: '➤', label: 'Rocket Shell' },
  grenade: { icon: '●', label: 'Grenade' },
  explosiveBarrel: { icon: '☢', label: 'Explosive Barrel' },
  primerBox: { icon: '⊟', label: 'Primer Box' },
  // Machinery
  assemblyArm: { icon: '⌐', label: 'Assembly Arm' },
  stamperPress: { icon: '⊥', label: 'Stamper Press' },
  industrialFan: { icon: '✳', label: 'Industrial Fan' },
  controlPanel: { icon: '▭', label: 'Control Panel' },
  hazardSign: { icon: '⚠', label: 'Hazard Sign' },
  conveyorAmmo: { icon: '═', label: 'Ammo Conveyor' },
};
